library(dplyr)
library(naniar)
df <- read.csv("~/R Projects/ExData_Plotting1/Data/household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
df2 <- filter(df, Date=="1/2/2007" | Date=="2/2/2007" )
rm(df)
df2 %>% replace_with_na_all(condition = ~.x== "?")
df2 <- mutate(df2,dt= paste(df2$Date, df2$Time))
df2$dt <- as.POSIXct(df2$dt, format="%d/%m/%Y %H:%M:%S")
df2$Global_active_power <-  as.numeric(df2$Global_active_power)
with(df2, plot(Global_active_power~dt, type= "l", ylab = "Global Active Power (killowatts)", xlab= ""))