library(dplyr)
library(naniar)
df <- read.csv("~/R Projects/ExData_Plotting1/Data/household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
df2 <- filter(df, Date=="1/2/2007" | Date=="2/2/2007" )
rm(df)
df2 %>% replace_with_na_all(condition = ~.x== "?")
df2 <- mutate(df2,dt= paste(df2$Date, df2$Time))
df2$dt <- as.POSIXct(df2$dt, format="%d/%m/%Y %H:%M:%S")
df2$df2$Sub_metering_1 <-  as.numeric(df2$df2$Sub_metering_1)
df2$df2$Sub_metering_2 <-  as.numeric(df2$df2$Sub_metering_2)
df2$df2$Sub_metering_3 <-  as.numeric(df2$df2$Sub_metering_3)
with(df2, plot(Sub_metering_1~dt, type= "n", ylab = "Energy Sub metering", xlab= ""))
lines(df2$dt,df2$Sub_metering_1, col="black")
lines(df2$dt,df2$Sub_metering_2, col="red")
lines(df2$dt,df2$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty = 1)